CREATE INDEX "audit_logs_performed_by_idx" ON "audit_logs" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "audit_logs_target_user_idx" ON "audit_logs" USING btree ("target_user");--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "audit_logs_action_idx" ON "audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "exam_answers_session_id_idx" ON "exam_answers" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "exam_answers_question_id_idx" ON "exam_answers" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "exam_assignments_exam_id_idx" ON "exam_assignments" USING btree ("exam_id");--> statement-breakpoint
CREATE INDEX "exam_assignments_student_id_idx" ON "exam_assignments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "exam_assignments_exam_student_idx" ON "exam_assignments" USING btree ("exam_id","student_id");--> statement-breakpoint
CREATE INDEX "exam_questions_exam_id_idx" ON "exam_questions" USING btree ("exam_id");--> statement-breakpoint
CREATE INDEX "exam_questions_question_id_idx" ON "exam_questions" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "exam_sessions_exam_id_idx" ON "exam_sessions" USING btree ("exam_id");--> statement-breakpoint
CREATE INDEX "exam_sessions_student_id_idx" ON "exam_sessions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "exam_sessions_status_idx" ON "exam_sessions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "exam_sessions_exam_student_idx" ON "exam_sessions" USING btree ("exam_id","student_id");--> statement-breakpoint
CREATE INDEX "exams_start_time_idx" ON "exams" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "exams_end_time_idx" ON "exams" USING btree ("end_time");--> statement-breakpoint
CREATE INDEX "exams_status_idx" ON "exams" USING btree ("status");--> statement-breakpoint
CREATE INDEX "exams_created_by_idx" ON "exams" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "exams_subject_idx" ON "exams" USING btree ("subject");--> statement-breakpoint
CREATE INDEX "proctoring_events_session_id_idx" ON "proctoring_events" USING btree ("proctoring_session_id");--> statement-breakpoint
CREATE INDEX "proctoring_events_timestamp_idx" ON "proctoring_events" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "proctoring_flags_session_id_idx" ON "proctoring_flags" USING btree ("proctoring_session_id");--> statement-breakpoint
CREATE INDEX "proctoring_flags_reviewed_idx" ON "proctoring_flags" USING btree ("reviewed");--> statement-breakpoint
CREATE INDEX "proctoring_flags_severity_idx" ON "proctoring_flags" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "proctoring_photos_session_id_idx" ON "proctoring_photos" USING btree ("proctoring_session_id");--> statement-breakpoint
CREATE INDEX "proctoring_sessions_session_id_idx" ON "proctoring_sessions" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "proctoring_sessions_student_id_idx" ON "proctoring_sessions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "proctoring_sessions_exam_id_idx" ON "proctoring_sessions" USING btree ("exam_id");--> statement-breakpoint
CREATE INDEX "proctoring_sessions_status_idx" ON "proctoring_sessions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "questions_subject_idx" ON "questions" USING btree ("subject");--> statement-breakpoint
CREATE INDEX "questions_topic_idx" ON "questions" USING btree ("topic");--> statement-breakpoint
CREATE INDEX "questions_status_idx" ON "questions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "questions_created_by_idx" ON "questions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_status_idx" ON "users" USING btree ("status");